
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Benchkart.Default" %>

<!DOCTYPE html>

<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-142828286-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-142828286-2');
    </script>
    <link rel="canonical" href="https://benchkart.com/">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>benchkart - Marketplace For Outsourcing</title>
    <meta content="Benchkart is a new age digital marketplace for procurement of digital B2B services. Get your work done by best IT & Digital agencies." name="description">
    <meta content="benchkart, marketplace for outsourcing, Graphics & Design,Website & Apps,Digital Marketing,Software,Cloud & Infra,Call Center,KPO,Back-Office," name="keywords">

    <meta property="og:url" content="https://benchkart.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Marketplace For Outsourcing | Benchkart" />
    <meta property="og:description" content="Benchkart is a new age digital marketplace for procurement of digital B2B services. Get your work done by best IT & Digital agencies." />
    <meta property="og:image" content="https://benchkart.com/Images/Benchkart_Card.jpg" />
    <meta property="og:site_name" content="Benchkart" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@Benchkart" />
    <meta name="twitter:title" content="Marketplace For Outsourcing | Benchkart" />
    <meta name="twitter:description" content="Benchkart is a new age digital marketplace for procurement of digital B2B services. Get your work done by best IT & Digital agencies." />
    <meta name="twitter:image" content="https://benchkart.com/Images/Benchkart_Card.jpg" />

    <!-- Favicons -->
    <link href="favicon.ico" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/vendor/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

    <%-- <script>

        // window.onload
        window.onload = function () {
            if (window != window.top) { //Checks whether the custom error page is loading inside an iframe
                window.top.location = window.location; //Set the top location to custom error page location
            }
        };



    </script>--%>
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "Product",
          "name" : "Procure B2B Services",
          "description" : "Benchkart is your one-stop shop for procurement of any digital services. We have India’s top rated mid-sized agencies across IT Services, Digital Marketing &amp; BPO as service providers. Our automated processes, project management support &amp; payment security help you get quality results while saving time &amp; money"
        }
    </script>
    <style>
        #header #logo h1 {
            font-size: 28px;
            letter-spacing: 1px;
        }

        @media (max-width: 1024px) {
            #header #logo h1 {
                font-size: 22px;
                letter-spacing: 1px;
            }

            #mobile-nav ul {
                width: 100%;
            }

                #mobile-nav ul li a {
                    padding: 15px 22px 15px 15px;
                }
        }

        @media (min-width: 1024px) {
            #header #logo {
                padding-left: 10px;
            }

            .nav-menu > li {
                margin-left: 15px;
            }
        }

        @media (min-width: 1024px) {
            #nav-menu-container {
                padding-right: 10px;
            }

            .nav-menu ul {
                left: -100px;
            }
        }

        .nav-menu a {
            padding: 0 4px 5px 4px;
        }

        #mobile-nav-toggle {
            right: 30px;
        }
    </style>
    <style>
        .dropbtn {
            color: white;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

            .dropbtn:hover, .dropbtn:focus {
                background-color: #18D26E;
            }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            left: -100px;
            display: none;
            position: absolute;
            background-color: white;
            min-width: 120px;
            margin-top: 5px;
            overflow: auto;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                padding: 10px;
                color: #333;
                transition: 0.3s;
                display: block;
                font-size: 13px;
                text-transform: none;
                font-weight: bold;
            }

        .dropdown a:hover {
            color: #18d26e;
        }

        .show {
            display: block;
        }
    </style>
    <script>
        /* When the user clicks on the button, 
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
    <%-- <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>--%>
</head>

<body>
    <form runat="server">

        <!-- ======= Header ======= -->
        <header id="header">
            <div class="container-fluid">

                <div id="logo" class="pull-left">
                    <h1><a href="https://benchkart.com" class="scrollto"><span style="color: #18D26E;">bench</span><span style="color: coral;">kart</span></a></h1>
                    <!-- Uncomment below if you prefer to use an image logo -->
                    <!-- <a href="#intro"><img src="assets/img/logo.png" alt=""></a>-->
                </div>
                <div style="float: right;">
                    <nav id="nav-menu-container" style="float: left;">
                        <ul class="nav-menu" style="float: left;">
                            <%--<li class="menu-active"><a href="#intro">Home</a></li>
                    <li><a href="#about">About Us</a></li>
                    <li><a href="#services">Services</a></li>
                    <li><a href="#portfolio">Portfolio</a></li>
                    <li><a href="#team">Team</a></li>--%>
                            <li class="menu-has-children">
                                <a href="#">Design</a>
                                <ul>
                                    <li><a href="Category?id=11">Logo Creation & Adaptation</a></li>
                                    <li><a href="Category?id=12">Social Media Design</a></li>
                                    <li><a href="Category?id=13">POSM Design</a></li>
                                    <li><a href="Category?id=14">Packaging Design</a></li>
                                    <li><a href="Category?id=15">Banner Ads</a></li>
                                    <li><a href="Category?id=16">Presentation Design</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>
                            <li class="menu-has-children"><a href="#">Website & Apps</a>
                                <ul>
                                    <li><a href="Category?id=18">Website Development</a></li>
                                    <li><a href="Category?id=19">Website Designing - UI/UX</a></li>
                                    <li><a href="Category?id=20">Website Maintenance</a></li>
                                    <li><a href="Category?id=21">Mobile Applications</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>

                            <li class="menu-has-children"><a href="#">Marketing</a>
                                <ul>
                                    <li><a href="Category?id=23">Digital Strategy</a></li>
                                    <li><a href="Category?id=24">Search Marketing</a></li>
                                    <li><a href="Category?id=25">Display Marketing</a></li>
                                    <li><a href="Category?id=26">E-mail Marketing</a></li>
                                    <li><a href="Category?id=27">Social Media Marketing</a></li>
                                    <li><a href="Category?id=28">Influencer Marketing</a></li>
                                    <li><a href="Category?id=29">Content Marketing</a></li>
                                    <li><a href="Category?id=30">Search Engine Optimization (SEO)</a></li>
                                    <li><a href="Category?id=31">Data Mining & Analytics</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>
                            <li class="menu-has-children"><a href="#">Software</a>
                                <ul>
                                    <li><a href="Category?id=33">Software Development</a></li>
                                    <li><a href="Category?id=34">SaaS Applications</a></li>
                                    <li><a href="Category?id=35">Testing & QA</a></li>
                                    <li><a href="Category?id=36">Maintenance & Support</a></li>
                                    <li><a href="Category?id=37">Cloud Computing Applications</a></li>
                                    <li><a href="Category?id=38">Integration & Migration Services</a></li>
                                    <li><a href="Category?id=39">Game Development</a></li>
                                    <li><a href="Category?id=40">IoT Solutions</a></li>
                                    <li><a href="Category?id=41">Chatbots</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>
                            <li class="menu-has-children"><a href="#">Cloud & Infra</a>
                                <ul>
                                    <li><a href="Category?id=43">Server Setup & Troubleshooting</a></li>
                                    <li><a href="Category?id=44">Server Management & Webmaster Services</a></li>
                                    <li><a href="Category?id=45">Network Setup And Management</a></li>
                                    <li><a href="Category?id=46">Remote IT Management</a></li>
                                    <li><a href="Category?id=47">Cloud Setup & Migration</a></li>
                                    <li><a href="Category?id=48">Cloud Consulting & Strategy</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>
                            <li class="menu-has-children"><a href="#">Call Center</a>
                                <ul>
                                    <li><a href="Category?id=50">Inbound Calling</a></li>
                                    <li><a href="Category?id=51">Outbound Calling</a></li>
                                    <li><a href="Category?id=52">Outbound - Debt Collection</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>
                            <li class="menu-has-children"><a href="#">KPO</a>
                                <ul>
                                    <li><a href="Category?id=54">Human Resources</a></li>
                                    <li><a href="Category?id=55">Business Strategy</a></li>
                                    <li><a href="Category?id=56">Legal</a></li>
                                    <li><a href="Category?id=57">Financial & Accounting</a></li>
                                    <li><a href="Category?id=58">Healthcare</a></li>
                                    <li><a href="Category?id=59">IT Consulting</a></li>
                                    <li><a href="Category?id=60">IT Training & Development</a></li>
                                    <li><a href="Category?id=61">Market Research</a></li>
                                    <li><a href="Category?id=62">Public Relations</a></li>
                                    <li><a href="#">Any Other</a></li>
                                </ul>
                            </li>
                            <li class="menu-has-children"><a href="#">Back Office</a>
                                <ul>
                                    <li><a href="Category?id=64">24X7 Chat</a></li>
                                    <li><a href="Category?id=65">Email Management</a></li>
                                    <li><a href="Category?id=66">Data Entry & Internet Research</a></li>
                                    <li><a href="Category?id=67">Data Processing</a></li>
                                    <li><a href="Category?id=68">Digitization</a></li>
                                    <li><a href="Category?id=69">Research & Analytics</a></li>
                                    <li><a href="Category?id=70">Offline & Online Catalogues </a></li>
                                    <li><a href="Category?id=71">Field Executive Support</a></li>
                                    <li><a href="Category?id=72">Writing & Translation Services</a></li>
                                    <li><a href="#">Any other</a></li>
                                </ul>
                            </li>


                        </ul>
                    </nav>

                    <div class="dropdown" style="float: right;">

                        <i onclick="myFunction()" style="font-size: 20px;" class="fa fa-user-circle dropbtn"></i>
                        <div id="myDropdown" class="dropdown-content">
                            <a href="Customer/Signin" class="nav-menu ul li a">Sign in</a>
                            <a href="Customer/Signup" class="nav-menu ul li a">Sign up</a>
                            <a href="Partner/Signup" class="nav-menu ul li a">For Partner</a>
                        </div>
                    </div>
                </div>


                <!-- #nav-menu-container -->
            </div>
        </header>
        <!-- End Header -->
        <%--<div id="snackbar1"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project on Social Media Marketing posted 18 hours ago...</div>
        <div id="snackbar2"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project is posted on Mobile Applications posted 6 hours ago...</div>
        <div id="snackbar3"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project is posted on Software Development posted 20 hours ago...</div>
        <div id="snackbar4"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A Free consultation request posted 12 hours ago...</div>
        <div id="snackbar5"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project is posted on Inbound Calling posted 10 hours ago...</div>
        <div id="snackbar6"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A Free consultation request posted 6 hours ago...</div>
        <div id="snackbar7"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project is posted on Outbound Calling posted 8 hours ago...</div>
        <div id="snackbar8"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project is posted on Logo Creation posted 7 hours ago...</div>
        <div id="snackbar9"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A Free consultation request posted 15 hours ago...</div>
        <div id="snackbar10"><i class="fa fa-paper-plane" style="color: #F79507;"></i>&nbsp;&nbsp;A project is posted on Search Engine Optimization posted 16 hours ago...</div>--%>

        <!-- ======= Intro Section ======= -->
        <section id="intro">
            <div class="intro-container">
                <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

                    <ol class="carousel-indicators"></ol>

                    <div class="carousel-inner" role="listbox">

                        <div class="carousel-item active">
                            <div class="carousel-background">
                                <img src="assets/img/intro-carousel/1.jpg" alt="procure">
                            </div>
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>Procure B2B Services</h2>
                                    <p>Find & work with the Right Agency for the Right Price. Get India’s finest agencies across Digital Marketing, IT Services & BPO to work for you.</p>
                                    <a href="Customer/Post_Project" class="btn-get-started scrollto">Post a Project</a>
                                    <a href="Customer/Book_Consultation" class="btn-get-started scrollto">Free Consultation</a>

                                    <%--<a href="Customer/Post_Talent" class="btn-get-started scrollto">Hire a Developer</a>--%>
                                </div>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <div class="carousel-background">
                                <img src="assets/img/intro-carousel/2.jpg" alt="post-projects">
                            </div>
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>Post Projects for Free</h2>
                                    <p>Find & work with the Right Agency for the Right Price. Get India’s finest agencies across Digital Marketing, IT Services & BPO to work for you.</p>
                                    <a href="Customer/Post_Project" class="btn-get-started scrollto">Post a Project</a>
                                    <a href="Customer/Book_Consultation" class="btn-get-started scrollto">Free Consultation</a>

                                    <%-- <a href="Customer/Post_Talent" class="btn-get-started scrollto">Hire a Developer</a>--%>
                                </div>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <div class="carousel-background">
                                <img src="assets/img/intro-carousel/3.jpg" alt="bids">
                            </div>
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>Get Competitive Bids</h2>
                                    <p>Find & work with the Right Agency for the Right Price. Get India’s finest agencies across Digital Marketing, IT Services & BPO to work for you.</p>
                                    <a href="Customer/Post_Project" class="btn-get-started scrollto">Post a Project</a>
                                    <a href="Customer/Book_Consultation" class="btn-get-started scrollto">Free Consultation</a>

                                    <%--<a href="Customer/Post_Talent" class="btn-get-started scrollto">Hire a Developer</a>--%>
                                </div>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <div class="carousel-background">
                                <img src="assets/img/intro-carousel/4.jpg" alt="agencies">
                            </div>
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>Engage Top Agencies</h2>
                                    <p>Find & work with the Right Agency for the Right Price. Get India’s finest agencies across Digital Marketing, IT Services & BPO to work for you.</p>
                                    <a href="Customer/Post_Project" class="btn-get-started scrollto">Post a Project</a>
                                    <a href="Customer/Book_Consultation" class="btn-get-started scrollto">Free Consultation</a>

                                    <%-- <a href="Customer/Post_Talent" class="btn-get-started scrollto">Hire a Developer</a>--%>
                                </div>
                            </div>
                        </div>

                        <div class="carousel-item">
                            <div class="carousel-background">
                                <img src="assets/img/intro-carousel/5.jpg" alt="money">
                            </div>
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>Save Time & Money</h2>
                                    <p>Find & work with the Right Agency for the Right Price. Get India’s finest agencies across Digital Marketing, IT Services & BPO to work for you.</p>
                                    <a href="Customer/Post_Project" class="btn-get-started scrollto">Post a Project</a>
                                    <a href="Customer/Book_Consultation" class="btn-get-started scrollto">Free Consultation</a>
                                    <%-- <a href="Customer/Post_Talent" class="btn-get-started scrollto">Hire a Developer</a>--%>
                                </div>
                            </div>
                        </div>
                    </div>

                    <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>

                    <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                </div>
            </div>
        </section>
        <!-- End Intro Section -->

        <main id="main">

            <!-- ======= Featured Services Section Section ======= -->
            <section id="featured-services">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-4 box">
                            <i class="ion-ios-bookmarks-outline"></i>
                            <h4 class="title"><a href="#">It is built for quality</a></h4>
                            <p class="description">We get work done only through reputed mid-sized agencies who have expertise in your project area</p>
                        </div>

                        <div class="col-lg-4 box box-bg">
                            <i class="ion-ios-stopwatch-outline"></i>
                            <h4 class="title"><a href="#">It saves you time & money</a></h4>
                            <p class="description">We help you get competitive bids from matched agencies within hours</p>
                        </div>

                        <div class="col-lg-4 box">
                            <i class="ion-ios-heart-outline"></i>
                            <h4 class="title"><a href="#">It is free!</a></h4>
                            <p class="description">Posting a project or Consulting with our advisors is absolutely free right now</p>
                        </div>

                    </div>
                </div>
            </section>
            <!-- End Featured Services Section -->
            <!-- ======= Call To Action Section ======= -->
            <section id="call-to-action" class="wow fadeIn">
                <div class="container text-center">
                    <h3>Don’t let COVID-19 push you down!</h3>
                    <p>Benchkart is helping 250+ businesses counter the impact of COVID-19. Learn from our framework & evaluate 5 things that you can do.</p>
                    <a class="cta-btn" href="Post-COVID">Learn More</a>
                </div>
            </section>
            <!-- End Call To Action Section -->
            <!-- ======= About Us Section ======= -->
            <section id="about">
                <div class="container">

                    <header class="section-header">
                        <h3>HOW IT WORKS</h3>
                        <p>Our platform is powered by strong partner onboarding processes, project matching algorithms and built-in security features.</p>
                    </header>

                    <div class="row about-cols">
                        <div class="col-md-4 wow fadeInUp">
                            <div class="about-col">
                                <div class="img">
                                    <img src="assets/img/about-mission.jpg" alt="mission" class="img-fluid">
                                    <div class="icon"><i class="ion-ios-speedometer-outline"></i></div>
                                </div>
                                <h2 class="title"><a href="#">Post Requirement</a></h2>
                                <p>
                                    Post your Project through the link above. Let our algorithms do all the work & get you the best agency proposals.
                                </p>
                            </div>
                        </div>

                        <div class="col-md-4 wow fadeInUp" data-wow-delay="0.1s">
                            <div class="about-col">
                                <div class="img">
                                    <img src="assets/img/about-plan.jpg" alt="agency" class="img-fluid">
                                    <div class="icon"><i class="ion-ios-list-outline"></i></div>
                                </div>
                                <h2 class="title"><a href="#">Select Agency</a></h2>
                                <p>
                                    Discuss & finalise the agency you want to work with. Record your expectations clearly with the agency & with your relationship manager.
                                </p>
                            </div>
                        </div>

                        <div class="col-md-4 wow fadeInUp" data-wow-delay="0.2s">
                            <div class="about-col">
                                <div class="img">
                                    <img src="assets/img/about-vision.jpg" alt="delivery" class="img-fluid">
                                    <div class="icon"><i class="ion-ios-eye-outline"></i></div>
                                </div>
                                <h2 class="title"><a href="#">Get Work done</a></h2>
                                <p>
                                    Use our secure payment system which ensures 100% security for your payments. Release payment only when you approve the work.
                                </p>
                            </div>
                        </div>

                    </div>

                </div>
            </section>
            <!-- End About Us Section -->

            <!-- ======= Services Section ======= -->
            <section id="services">
                <div class="container">

                    <header class="section-header wow fadeInUp">
                        <h3>Why Agencies</h3>
                        <p>Organizations typically outsource their digital projects either to individual freelancers or to agencies. We have focused on a network of reputed & innovative mid-sized agencies as they are better in.</p>
                    </header>

                    <div class="row">

                        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
                            <div class="icon"><i class="ion-ribbon-a"></i></div>
                            <h4 class="title"><a href="">Quality</a></h4>
                            <p class="description">Too many freelancers; finding good quality may be a challenge. Benchkart agencies, on the other hand, have a pool of talent & are rated by renowned independent bodies</p>
                        </div>
                        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
                            <div class="icon"><i class="ion-network"></i></div>
                            <h4 class="title"><a href="">Reliability</a></h4>
                            <p class="description">Benchkart agencies are business houses, thereby mitigating risks associated with a single individual who may disappear, miss deadlines or perform sub-optimally</p>
                        </div>
                        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-duration="1.4s">
                            <div class="icon"><i class="ion-speedometer"></i></div>
                            <h4 class="title"><a href="">Value</a></h4>
                            <p class="description">While it may be possible to find individuals willing to work for lower upfront cost, but the overall value may get impacted due to delays & rework</p>
                        </div>
                        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
                            <div class="icon"><i class="ion-compass"></i></div>
                            <h4 class="title"><a href="">Complex Projects</a></h4>
                            <p class="description">Projects which are of longer duration or which require more than one resource or skills are better done through our agencies</p>
                        </div>
                        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
                            <div class="icon"><i class="ion-headphone"></i></div>
                            <h4 class="title"><a href="">Post Project Support</a></h4>
                            <p class="description">Our agencies have processes and teams for escalations & support which individual freelancers may not be able/available to provide</p>
                        </div>
                        <div class="col-lg-4 col-md-6 box wow bounceInUp" data-wow-delay="0.1s" data-wow-duration="1.4s">
                        </div>

                    </div>

                </div>
            </section>
            <!-- End Services Section -->


            <!-- ======= Skills Section ======= -->
            <%--<section id="skills">
            <div class="container">

                <header class="section-header">
                    <h3>Our Skills</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
                </header>

                <div class="skills-content">

                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100">
                            <span class="skill">HTML <i class="val">100%</i></span>
                        </div>
                    </div>

                    <div class="progress">
                        <div class="progress-bar bg-info" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100">
                            <span class="skill">CSS <i class="val">90%</i></span>
                        </div>
                    </div>

                    <div class="progress">
                        <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
                            <span class="skill">JavaScript <i class="val">75%</i></span>
                        </div>
                    </div>

                    <div class="progress">
                        <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100">
                            <span class="skill">Photoshop <i class="val">55%</i></span>
                        </div>
                    </div>

                </div>

            </div>
        </section>--%>
            <!-- End Skills Section -->

            <!-- ======= Facts Section ======= -->
            <section id="facts" class="wow fadeIn">
                <div class="container">

                    <header class="section-header">
                        <h3>Facts</h3>
                        <p>Number of Agencies we are partnering with to help businesses grow digitally</p>
                    </header>

                    <div class="row counters">

                        <div class="col-lg-3 col-6 text-center">
                            <span data-toggle="counter-up">185</span>
                            <p>Website Development</p>
                        </div>

                        <div class="col-lg-3 col-6 text-center">
                            <span data-toggle="counter-up">139</span>
                            <p>Digital Marketing</p>
                        </div>

                        <div class="col-lg-3 col-6 text-center">
                            <span data-toggle="counter-up">116</span>
                            <p>Software Development</p>
                        </div>

                        <div class="col-lg-3 col-6 text-center">
                            <span data-toggle="counter-up">118</span>
                            <p>Cloud Computing</p>
                        </div>

                    </div>

                    <%-- <div class="facts-img">
                    <img src="assets/img/facts-img.png" alt="" class="img-fluid">
                </div>--%>
                </div>
            </section>
            <!-- End Facts Section -->



            <!-- ======= Call To Action Section ======= -->
            <%-- <section id="Media" class="wow fadeIn" style="visibility: visible;animation-name: fadeIn;">
                <div class="container text-center">
                    <h3>Media Coverage</h3>
                    <p>We see SMEs struggling every day to find the right partners for their website projects, mobile applications, digital marketing, or cloud migration” Digital First Magazine covers the Benchkart story.</p>
                    <a class="cta-btn" href="https://www.digitalfirstmagazine.com/benchkart/" target="_blank">Read More</a>
                </div>
            </section>--%>
            <!-- End Call To Action Section -->

            <!-- ======= Portfolio Section ======= -->
            <section id="portfolio" class="section-bg">
                <div class="container">

                    <header class="section-header">
                        <h3 class="section-title">Popular Services</h3>
                    </header>

                    <%-- <div class="row">
                    <div class="col-lg-12">
                        <ul id="portfolio-flters">
                            <li data-filter="*" class="filter-active">All</li>
                            <li data-filter=".filter-app">App</li>
                            <li data-filter=".filter-card">Card</li>
                            <li data-filter=".filter-web">Web</li>
                        </ul>
                    </div>
                </div>--%>

                    <div class="row portfolio-container">

                        <%--<div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/1.png" class="img-fluid" alt="logo">
                                    <a href="Category?id=11" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=11">Logo Creation</a></h4>
                                    <p>Design</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/2.png" class="img-fluid" alt="presentation">
                                    <a href="Category?id=16" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=16">Presentation Design</a></h4>
                                    <p>Design</p>
                                </div>
                            </div>
                        </div>--%>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/3.png" class="img-fluid" alt="website">
                                    <%--<a href="Customer/Post_Project?id=18" class="link-preview venobox" data-gall="portfolioGallery" title="Website Development"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=18" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=18">Website Development</a></h4>
                                    <p>Website / Apps</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/7.png" class="img-fluid" alt="seo">
                                    <%--<a href="Customer/Post_Project?id=30" class="link-preview venobox" data-gall="portfolioGallery" title="Search Engine Optimization"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=30" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=30">Search Engine Optimization</a></h4>
                                    <p>Digital Marketing</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.1s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/8.png" class="img-fluid" alt="social-marketing">
                                    <%--<a href="Customer/Post_Project?id=27" class="link-preview venobox" data-gall="portfolioGallery" title="Social Marketing"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=27" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=27">Social Media Marketing</a></h4>
                                    <p>Digital Marketing</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-app wow fadeInUp" data-wow-delay="0.2s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/9.png" class="img-fluid" alt="mobile-apps">
                                    <%--<a href="Customer/Post_Project?id=21" class="link-preview venobox" data-gall="portfolioGallery" title="Mobile Applications"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=21" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=21">Mobile Applications</a></h4>
                                    <p>Website & Apps</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/10.png" class="img-fluid" alt="software">
                                    <%-- <a href="style/images/10.png" class="link-preview venobox" data-gall="portfolioGallery" title="Software Development"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=33" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=33">Software Development</a></h4>
                                    <p>Software</p>
                                </div>
                            </div>
                        </div>

                         <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp" data-wow-delay="0.1s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/11.png" class="img-fluid" alt="cloud-computing">
                                    
                                    <a href="Category?id=37" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=37">Cloud Computing</a></h4>
                                    <p>Cloud & Infra</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.2s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/12.png" class="img-fluid" alt="cloud-consulting">
                                    
                                    <a href="Category?id=48" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=48">Cloud Consulting</a></h4>
                                    <p>Cloud & Infra</p>
                                </div>
                            </div>
                        </div>

                       <%-- <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/13.png" class="img-fluid" alt="remote-it">
                                    
                                    <a href="Category?id=46" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=46">Remote IT Management</a></h4>
                                    <p>Cloud & Infra</p>
                                </div>
                            </div>
                        </div>--%>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-card wow fadeInUp" data-wow-delay="0.1s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/14.png" class="img-fluid" alt="inboud-calling">
                                    <%--<a href="style/images/14.png" class="link-preview venobox" data-gall="portfolioGallery" title="Inbound Calling"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=50" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=50">Inbound Calling</a></h4>
                                    <p>Call Center</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4 col-md-6 portfolio-item filter-web wow fadeInUp" data-wow-delay="0.2s">
                            <div class="portfolio-wrap">
                                <figure>
                                    <img src="style/images/15.png" class="img-fluid" alt="outbound-calling">
                                    <%--<a href="Customer/Post_Project?id=51" class="link-details" title="Outbound Calling"><i class="ion ion-eye"></i></a>--%>
                                    <a href="Category?id=51" class="link-details" title="Post Project"><i class="ion ion-android-open"></i></a>
                                </figure>

                                <div class="portfolio-info">
                                    <h4><a href="Category?id=51">Outbound Calling</a></h4>
                                    <p>Call Center</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- End Portfolio Section -->

            <!-- ======= Our Clients Section ======= -->
            <section id="clients" class="wow fadeInUp">
                <div class="container">

                    <header class="section-header">
                        <h3>Media Coverage</h3>
                    </header>
                    <p>We see SMEs struggling every day to find the right partners for their website projects, mobile applications, digital marketing, or cloud migration” Digital First Magazine covers the Benchkart story.</p>
                    <a class="cta-btn" href="https://www.digitalfirstmagazine.com/benchkart/" target="_blank" style="text-decoration: underline;">Read More</a>
                    <%-- <div class="owl-carousel clients-carousel">
                    <img src="assets/img/clients/client-1.png" alt="">
                    <img src="assets/img/clients/client-2.png" alt="">
                    <img src="assets/img/clients/client-3.png" alt="">
                    <img src="assets/img/clients/client-4.png" alt="">
                    <img src="assets/img/clients/client-5.png" alt="">
                    <img src="assets/img/clients/client-6.png" alt="">
                    <img src="assets/img/clients/client-7.png" alt="">
                    <img src="assets/img/clients/client-8.png" alt="">
                </div>--%>
                </div>
            </section>
            <!-- End Our Clients Section -->

            <!-- ======= Testimonials Section ======= -->
            <%--<section id="testimonials" class="section-bg wow fadeInUp">
            <div class="container">

                <header class="section-header">
                    <h3>Testimonials</h3>
                </header>

                <div class="owl-carousel testimonials-carousel">

                    <div class="testimonial-item">
                        <img src="assets/img/testimonial-1.jpg" class="testimonial-img" alt="">
                        <h3>Saul Goodman</h3>
                        <h4>Ceo &amp; Founder</h4>
                        <p>
                            <img src="assets/img/quote-sign-left.png" class="quote-sign-left" alt="">
                            Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
              <img src="assets/img/quote-sign-right.png" class="quote-sign-right" alt="">
                        </p>
                    </div>

                    <div class="testimonial-item">
                        <img src="assets/img/testimonial-2.jpg" class="testimonial-img" alt="">
                        <h3>Sara Wilsson</h3>
                        <h4>Designer</h4>
                        <p>
                            <img src="assets/img/quote-sign-left.png" class="quote-sign-left" alt="">
                            Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
              <img src="assets/img/quote-sign-right.png" class="quote-sign-right" alt="">
                        </p>
                    </div>

                    <div class="testimonial-item">
                        <img src="assets/img/testimonial-3.jpg" class="testimonial-img" alt="">
                        <h3>Jena Karlis</h3>
                        <h4>Store Owner</h4>
                        <p>
                            <img src="assets/img/quote-sign-left.png" class="quote-sign-left" alt="">
                            Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
              <img src="assets/img/quote-sign-right.png" class="quote-sign-right" alt="">
                        </p>
                    </div>

                    <div class="testimonial-item">
                        <img src="assets/img/testimonial-4.jpg" class="testimonial-img" alt="">
                        <h3>Matt Brandon</h3>
                        <h4>Freelancer</h4>
                        <p>
                            <img src="assets/img/quote-sign-left.png" class="quote-sign-left" alt="">
                            Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
              <img src="assets/img/quote-sign-right.png" class="quote-sign-right" alt="">
                        </p>
                    </div>

                    <div class="testimonial-item">
                        <img src="assets/img/testimonial-5.jpg" class="testimonial-img" alt="">
                        <h3>John Larson</h3>
                        <h4>Entrepreneur</h4>
                        <p>
                            <img src="assets/img/quote-sign-left.png" class="quote-sign-left" alt="">
                            Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
              <img src="assets/img/quote-sign-right.png" class="quote-sign-right" alt="">
                        </p>
                    </div>

                </div>

            </div>
        </section>--%>
            <!-- End Testimonials Section -->

            <!-- ======= Team Section ======= -->
            <%-- <section id="team">
            <div class="container">
                <div class="section-header wow fadeInUp">
                    <h3>Team</h3>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
                </div>

                <div class="row">

                    <div class="col-lg-3 col-md-6 wow fadeInUp">
                        <div class="member">
                            <img src="assets/img/team-1.jpg" class="img-fluid" alt="">
                            <div class="member-info">
                                <div class="member-info-content">
                                    <h4>Walter White</h4>
                                    <span>Chief Executive Officer</span>
                                    <div class="social">
                                        <a href=""><i class="fa fa-twitter"></i></a>
                                        <a href=""><i class="fa fa-facebook"></i></a>
                                        <a href=""><i class="fa fa-google-plus"></i></a>
                                        <a href=""><i class="fa fa-linkedin"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="member">
                            <img src="assets/img/team-2.jpg" class="img-fluid" alt="">
                            <div class="member-info">
                                <div class="member-info-content">
                                    <h4>Sarah Jhonson</h4>
                                    <span>Product Manager</span>
                                    <div class="social">
                                        <a href=""><i class="fa fa-twitter"></i></a>
                                        <a href=""><i class="fa fa-facebook"></i></a>
                                        <a href=""><i class="fa fa-google-plus"></i></a>
                                        <a href=""><i class="fa fa-linkedin"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                        <div class="member">
                            <img src="assets/img/team-3.jpg" class="img-fluid" alt="">
                            <div class="member-info">
                                <div class="member-info-content">
                                    <h4>William Anderson</h4>
                                    <span>CTO</span>
                                    <div class="social">
                                        <a href=""><i class="fa fa-twitter"></i></a>
                                        <a href=""><i class="fa fa-facebook"></i></a>
                                        <a href=""><i class="fa fa-google-plus"></i></a>
                                        <a href=""><i class="fa fa-linkedin"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                        <div class="member">
                            <img src="assets/img/team-4.jpg" class="img-fluid" alt="">
                            <div class="member-info">
                                <div class="member-info-content">
                                    <h4>Amanda Jepson</h4>
                                    <span>Accountant</span>
                                    <div class="social">
                                        <a href=""><i class="fa fa-twitter"></i></a>
                                        <a href=""><i class="fa fa-facebook"></i></a>
                                        <a href=""><i class="fa fa-google-plus"></i></a>
                                        <a href=""><i class="fa fa-linkedin"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </section>--%>
            <!-- End Team Section -->

            <!-- ======= Contact Section ======= -->
            <%-- <section id="contact" class="section-bg wow fadeInUp">
                <div class="container">

                    <div class="section-header">
                        <h3>Contact Us</h3>
                    </div>

                    <div class="row contact-info">
                        <div class="col-md-4">
                            <div class="contact-address">
                                <i class="ion-ios-location-outline"></i>
                                <h3>Address</h3>
                                <address>DW 254, Nirvana Country, Gurgaon, India</address>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="contact-phone">
                                <i class="ion-ios-telephone-outline"></i>
                                <h3>Phone Number</h3>
                                <p><a href="tel:+919911780051">+91 9911780051</a></p>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="contact-email">
                                <i class="ion-ios-email-outline"></i>
                                <h3>Email</h3>
                                <p><a href="mailto:info@example.com">outsource@benchkart.com</a></p>
                            </div>
                        </div>

                    </div>

                    <div class="form">

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <asp:TextBox runat="server" type="text" name="name" class="form-control" ID="name" placeholder="Your Name" Style="font-size: small;" />
                                <asp:RequiredFieldValidator ID="reqname" Display="Dynamic" ForeColor="Red" Font-Size="Small"
                                    ValidationGroup="SubmitMessage" runat="server" SetFocusOnError="True" ControlToValidate="name"
                                    Text="Please type your name" ErrorMessage="Please type your name."></asp:RequiredFieldValidator>
                            </div>
                            <div class="form-group col-md-6">
                                <asp:TextBox runat="server" type="email" class="form-control" name="email" ID="email" placeholder="Your Email" Style="font-size: small;" />
                                <asp:RequiredFieldValidator ID="reqemail" Display="Dynamic" ForeColor="Red" Font-Size="Small"
                                    ValidationGroup="SubmitMessage" runat="server" SetFocusOnError="True" ControlToValidate="email"
                                    Text="Please type your email" ErrorMessage="Please type your email"></asp:RequiredFieldValidator>
                                <asp:RegularExpressionValidator ID="regemail" runat="server" ControlToValidate="email" Font-Size="Small"
                                    ForeColor="Red" ValidationExpression="^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$"
                                    Display="Dynamic" ErrorMessage="Invalid email address" />
                            </div>
                        </div>
                        <div class="form-group">
                            <asp:TextBox runat="server" type="text" class="form-control" name="subject" ID="subject" placeholder="Subject" Style="font-size: small;" />
                            <asp:RequiredFieldValidator ID="reqsubject" Display="Dynamic" ForeColor="Red" Font-Size="Small"
                                ValidationGroup="SubmitMessage" runat="server" SetFocusOnError="True" ControlToValidate="subject"
                                Text="Please type subject" ErrorMessage="Please type subject"></asp:RequiredFieldValidator>
                        </div>
                        <div class="form-group">
                            <asp:TextBox runat="server" TextMode="MultiLine" class="form-control" name="message" ID="message" Rows="5" placeholder="Message" Style="font-size: small;"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="reqmessage" Display="Dynamic" ForeColor="Red" Font-Size="Small"
                                ValidationGroup="SubmitMessage" runat="server" SetFocusOnError="True" ControlToValidate="message"
                                Text="Please type message" ErrorMessage="Please type message"></asp:RequiredFieldValidator>
                        </div>
                        <div class="text-center">
                            <asp:Button runat="server" ID="btnSendMessage" ValidationGroup="SubmitMessage" type="submit" OnClick="btnSendMessage_Click" Text="Send Message" Style="background-color: #18D26E; padding: 8px 16px; color: white;"></asp:Button>
                        </div>
                    </div>
                </div>
            </section>--%>
            <!-- End Contact Section -->

        </main><!-- End #main -->

        <!-- ======= Footer ======= -->
        <footer id="footer">
            <div class="footer-top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-3 col-md-6 footer-info">
                            <h1>benchkart</h1>
                            <p>Benchkart is a new age digital marketplace for procurement of digital B2B services. Founded by an erstwhile member of Microsoft India Leadership, we are committed to solving the challenges in procurement of services, especially for start-ups and small businesses across the world.</p>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Useful Links</h4>
                            <ul>
                                <li><i class="ion-ios-arrow-right"></i><a href="#">Home</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="About" target="_blank">About us</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Html/Faq.html" target="_blank">FAQs</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Partner/Signup">Become a Partner</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Policies/Terms-of-use-for-Clients.html" target="_blank">TERMS OF USE FOR CLIENTS</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Policies/Terms-of-use-for-Partners.html" target="_blank">TERMS OF USE FOR PARTNERS</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Policies/Benchkart-Privacy-Policy.html" target="_blank">PRIVACY POLICY</a></li>

                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-contact">
                            <h4>Contact Us</h4>
                            <p>
                                DW 254, Nirvana Country
                            <br>
                                Gurgaon, Haryana  122018<br>
                                India
                            <br>
                                <strong>Phone:</strong> +91 9911780051<br>
                                <strong>Email:</strong> outsource@benchkart.com<br>
                            </p>

                            <div class="social-links">
                                <a href="https://twitter.com/benchkart?ref_src=twsrc%5Etfw" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a>
                                <a href="https://facebook.com/benchkart-111486960437160" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a>
                                <%--<a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>--%>
                                <a href="https://linkedin.com/company/benchkart" class="linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>
                            </div>

                        </div>

                        <div class="col-lg-3 col-md-6 footer-newsletter">
                            <h4>BECOME A PARTNER</h4>
                            <p>We are inviting only a few of India's top rated (mid-sized) agencies to join the benchkart platform. If you feel your domain expertise & innovation can add value to our customers, please let our assessment team know.</p>
                            <%--<form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>--%>
                        </div>

                    </div>
                </div>
            </div>

            <div class="container">
                <div class="copyright">
                    &copy; Copyright <strong>2020 Benchkart Services Pvt Ltd</strong>. All Rights Reserved
                </div>
                <div class="credits">
                </div>
            </div>
            <!--Start of Tawk.to Script-->
            <%--<script type="text/javascript">
                var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
                (function () {
                    var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
                    s1.async = true;
                    s1.src = 'https://embed.tawk.to/5d983f3fdb28311764d765fe/default';
                    s1.charset = 'UTF-8';
                    s1.setAttribute('crossorigin', '*');
                    s0.parentNode.insertBefore(s1, s0);
                })();
            </script>--%>
            <!--End of Tawk.to Script-->



        </footer>
        <!-- End Footer -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        <!-- Uncomment below i you want to use a preloader -->
        <!-- <div id="preloader"></div> -->

        <!-- Vendor JS Files -->
        <script src="assets/vendor/jquery/jquery.min.js"></script>
        <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
        <script src="assets/vendor/php-email-form/validate.js"></script>
        <script src="assets/vendor/wow/wow.min.js"></script>
        <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
        <script src="assets/vendor/counterup/counterup.min.js"></script>
        <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="assets/vendor/venobox/venobox.min.js"></script>
        <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
        <script src="assets/vendor/superfish/superfish.min.js"></script>
        <script src="assets/vendor/hoverIntent/hoverIntent.js"></script>
        <script src="assets/vendor/jquery-touchswipe/jquery.touchSwipe.min.js"></script>

        <!-- Template Main JS File -->
        <script src="assets/js/main.js"></script>
        <script type="text/javascript"> _linkedin_partner_id = "1009091"; window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || []; window._linkedin_data_partner_ids.push(_linkedin_partner_id); </script>
        <script type="text/javascript"> (function () { var s = document.getElementsByTagName("script")[0]; var b = document.createElement("script"); b.type = "text/javascript"; b.async = true; b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js"; s.parentNode.insertBefore(b, s); })(); </script>
        <noscript>
            <img height="1" width="1" style="display: none;" alt="linkedin" src="https://px.ads.linkedin.com/collect/?pid=1009091&fmt=gif" />
        </noscript>
    </form>
</body>

</html>
