version: '3.4'

services:
  benchkart:
    image: benchkart:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - :C:\inetpub\wwwroot
      - ~\msvsmon:C:\msvsmon:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
