
<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Error.aspx.cs" Inherits="Benchkart.Error" %>

<!DOCTYPE html>

<html lang="en">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <% if(!Benchkart.AppSettings.isDevelopmentMode()) { %>
            <script async src="https://www.googletagmanager.com/gtag/js?id=UA-142828286-2"></script>
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());

            gtag('config', 'UA-142828286-2');
    <% } %>
    <link rel="canonical" href="https://benchkart.com/">
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>benchkart - Marketplace For Outsourcing</title>
    <meta content="Benchkart is a new age digital marketplace for procurement of digital B2B services. Get your work done by best IT & Digital agencies." name="description">
    <meta content="benchkart, marketplace for outsourcing, Graphics & Design,Website & Apps,Digital Marketing,Software,Cloud & Infra,Call Center,KPO,Back-Office," name="keywords">

    <meta property="og:url" content="https://benchkart.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="Marketplace For Outsourcing | Benchkart" />
    <meta property="og:description" content="Benchkart is a new age digital marketplace for procurement of digital B2B services. Get your work done by best IT & Digital agencies." />
    <meta property="og:image" content="https://benchkart.com/Images/Benchkart_Card.jpg" />
    <meta property="og:site_name" content="Benchkart" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@Benchkart" />
    <meta name="twitter:title" content="Marketplace For Outsourcing | Benchkart" />
    <meta name="twitter:description" content="Benchkart is a new age digital marketplace for procurement of digital B2B services. Get your work done by best IT & Digital agencies." />
    <meta name="twitter:image" content="https://benchkart.com/Images/Benchkart_Card.jpg" />

    <!-- Favicons -->
    <link href="favicon.ico" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="assets/vendor/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="assets/css/style.css" rel="stylesheet">

    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
  
    <style>
        #header #logo h1 {
            font-size: 28px;
            letter-spacing: 1px;
        }

        @media (max-width: 1024px) {
            #header #logo h1 {
                font-size: 22px;
                letter-spacing: 1px;
            }

            #mobile-nav ul {
                width: 100%;
            }

                #mobile-nav ul li a {
                    padding: 15px 22px 15px 15px;
                }
        }

        @media (min-width: 1024px) {
            #header #logo {
                padding-left: 10px;
            }

            .nav-menu > li {
                margin-left: 15px;
            }
        }

        @media (min-width: 1024px) {
            #nav-menu-container {
                padding-right: 10px;
            }

            .nav-menu ul {
                left: -100px;
            }
        }

        .nav-menu a {
            padding: 0 4px 5px 4px;
        }

        #mobile-nav-toggle {
            right: 30px;
        }
    </style>
    <style>
        .dropbtn {
            color: white;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

            .dropbtn:hover, .dropbtn:focus {
                background-color: #18D26E;
            }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            left: -100px;
            display: none;
            position: absolute;
            background-color: white;
            min-width: 120px;
            margin-top: 5px;
            overflow: auto;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                padding: 10px;
                color: #333;
                transition: 0.3s;
                display: block;
                font-size: 13px;
                text-transform: none;
                font-weight: bold;
            }

        .dropdown a:hover {
            color: #18d26e;
        }

        .show {
            display: block;
        }
    </style>
    <script>
        /* When the user clicks on the button, 
        toggle between hiding and showing the dropdown content */
        function myFunction() {
            document.getElementById("myDropdown").classList.toggle("show");
        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
    <%-- <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>--%>
</head>

<body>
    <form runat="server">

        <!-- ======= Header ======= -->
        <header id="header">
            <div class="container-fluid">

                <div id="logo" class="pull-left">
                    <h1><a href="https://benchkart.com" class="scrollto"><span style="color: #18D26E;">bench</span><span style="color: coral;">kart</span></a></h1>
                    <!-- Uncomment below if you prefer to use an image logo -->
                    <!-- <a href="#intro"><img src="assets/img/logo.png" alt=""></a>-->
                </div>
                <div style="float: right;">
                    

                    <div class="dropdown" style="float: right;">

                        <i onclick="myFunction()" style="font-size: 20px;" class="fa fa-user-circle dropbtn"></i>
                        <div id="myDropdown" class="dropdown-content">
                            <a href="Customer/Signin" class="nav-menu ul li a">Sign in</a>
                            <a href="Customer/Signup" class="nav-menu ul li a">Sign up</a>
                            <a href="Partner/Signup" class="nav-menu ul li a">For Partner</a>
                        </div>
                    </div>
                </div>


                <!-- #nav-menu-container -->
            </div>
        </header>
      
        <!-- ======= Intro Section ======= -->
        <section id="intro">
            <div class="intro-container">
              <%--  <div class="intro-container">
                    <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">
                         <h3>An error occured while processing the request. We have captured the relevant information and will get on it. Meanwhile, please navigate to <a href="/">home</a></h3>
                    </div>
                </div>--%>

                 <div class="intro-container">
                <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <div class="carousel-background">
                                <img src="assets/img/intro-carousel/1.jpg" alt="procure">
                            </div>
                            <div class="carousel-container">
                                <div class="carousel-content">
                                    <h2>Error !</h2>
                                    <p>An error occured while processing the request. We have captured the relevant information and will get on it. Meanwhile, please navigate to <a href="/">home</a></p>
                                    <a href="Customer/Post_Project" class="btn-get-started scrollto">Start a new Project</a>
                                    <a href="Customer/Book_Consultation" class="btn-get-started scrollto">Request Consultation</a>

                                    <%--<a href="Customer/Post_Talent" class="btn-get-started scrollto">Hire a Developer</a>--%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </section>
        <!-- End Intro Section -->

        <main id="main">

            <!-- ======= Featured Services Section Section ======= -->
            <section id="featured-services">
                <div class="container">
                  
                </div>
            </section>
            
        </main><!-- End #main -->

        <!-- ======= Footer ======= -->
        <footer id="footer">
            <div class="footer-top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-3 col-md-6 footer-info">
                            <h1>benchkart</h1>
                            <p>Benchkart is a new age digital marketplace for procurement of digital B2B services. Founded by an erstwhile member of Microsoft India Leadership, we are committed to solving the challenges in procurement of services, especially for start-ups and small businesses across the world.</p>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-links">
                            <h4>Useful Links</h4>
                            <ul>
                                <li><i class="ion-ios-arrow-right"></i><a href="#">Home</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="About" target="_blank">About us</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Html/Faq.html" target="_blank">FAQs</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Partner/Signup">Become a Partner</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Policies/Terms-of-use-for-Clients.html" target="_blank">TERMS OF USE FOR CLIENTS</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Policies/Terms-of-use-for-Partners.html" target="_blank">TERMS OF USE FOR PARTNERS</a></li>
                                <li><i class="ion-ios-arrow-right"></i><a href="Policies/Benchkart-Privacy-Policy.html" target="_blank">PRIVACY POLICY</a></li>

                            </ul>
                        </div>

                        <div class="col-lg-3 col-md-6 footer-contact">
                            <h4>Contact Us</h4>
                            <p>
                                DW 254, Nirvana Country
                            <br>
                                Gurgaon, Haryana  122018<br>
                                India
                            <br>
                                <strong>Phone:</strong> +91 9911780051<br>
                                <strong>Email:</strong> outsource@benchkart.com<br>
                            </p>

                            <div class="social-links">
                                <a href="https://twitter.com/benchkart?ref_src=twsrc%5Etfw" target="_blank" class="twitter"><i class="fa fa-twitter"></i></a>
                                <a href="https://facebook.com/benchkart-111486960437160" target="_blank" class="facebook"><i class="fa fa-facebook"></i></a>
                                <%--<a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                            <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>--%>
                                <a href="https://linkedin.com/company/benchkart" class="linkedin" target="_blank"><i class="fa fa-linkedin"></i></a>
                            </div>

                        </div>

                        <div class="col-lg-3 col-md-6 footer-newsletter">
                            <h4>BECOME A PARTNER</h4>
                            <p>We are inviting only a few of India's top rated (mid-sized) agencies to join the benchkart platform. If you feel your domain expertise & innovation can add value to our customers, please let our assessment team know.</p>
                            <%--<form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>--%>
                        </div>

                    </div>
                </div>
            </div>

            <div class="container">
                <div class="copyright">
                    &copy; Copyright <strong>2020 Benchkart Services Pvt Ltd</strong>. All Rights Reserved
                </div>
                <div class="credits">
                </div>
            </div>
            <!--Start of Tawk.to Script-->
            <%--<script type="text/javascript">
                var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
                (function () {
                    var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
                    s1.async = true;
                    s1.src = 'https://embed.tawk.to/5d983f3fdb28311764d765fe/default';
                    s1.charset = 'UTF-8';
                    s1.setAttribute('crossorigin', '*');
                    s0.parentNode.insertBefore(s1, s0);
                })();
            </script>--%>
            <!--End of Tawk.to Script-->



        </footer>
        <!-- End Footer -->

        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        <!-- Uncomment below i you want to use a preloader -->
        <!-- <div id="preloader"></div> -->

        <!-- Vendor JS Files -->
        <script src="assets/vendor/jquery/jquery.min.js"></script>
        <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/vendor/jquery.easing/jquery.easing.min.js"></script>
        <script src="assets/vendor/php-email-form/validate.js"></script>
        <script src="assets/vendor/wow/wow.min.js"></script>
        <script src="assets/vendor/waypoints/jquery.waypoints.min.js"></script>
        <script src="assets/vendor/counterup/counterup.min.js"></script>
        <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
        <script src="assets/vendor/venobox/venobox.min.js"></script>
        <script src="assets/vendor/owl.carousel/owl.carousel.min.js"></script>
        <script src="assets/vendor/superfish/superfish.min.js"></script>
        <script src="assets/vendor/hoverIntent/hoverIntent.js"></script>
        <script src="assets/vendor/jquery-touchswipe/jquery.touchSwipe.min.js"></script>

        <!-- Template Main JS File -->
        <script src="assets/js/main.js"></script>
        <script type="text/javascript"> _linkedin_partner_id = "1009091"; window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || []; window._linkedin_data_partner_ids.push(_linkedin_partner_id); </script>
        <script type="text/javascript"> (function () { var s = document.getElementsByTagName("script")[0]; var b = document.createElement("script"); b.type = "text/javascript"; b.async = true; b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js"; s.parentNode.insertBefore(b, s); })(); </script>
        <noscript>
            <img height="1" width="1" style="display: none;" alt="linkedin" src="https://px.ads.linkedin.com/collect/?pid=1009091&fmt=gif" />
        </noscript>
    </form>
</body>

</html>
